/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : string,
  'status' : InquiryStatus,
  'inquiryType' : InquiryType,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
  'amount' : [] | [bigint],
}
export type InquiryStatus = { 'pending' : null } |
  { 'contacted' : null } |
  { 'reviewed' : null };
export type InquiryType = { 'investment' : null } |
  { 'loanApplication' : null };
export interface Member {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : Role,
  'photoUrl' : [] | [string],
  'email' : string,
  'address' : [] | [string],
  'phone' : string,
  'parentId' : [] | [string],
}
export type Role = { 'managingDirector' : null } |
  { 'director' : null } |
  { 'teamLeader' : null } |
  { 'marketingManager' : null } |
  { 'bizDev' : null };
export interface SalaryDistributionInput {
  'month' : bigint,
  'year' : bigint,
  'entries' : Array<
    { 'memberId' : string, 'notes' : [] | [string], 'amount' : bigint }
  >,
}
export interface SalaryInput {
  'memberId' : string,
  'month' : bigint,
  'year' : bigint,
  'notes' : [] | [string],
  'amount' : bigint,
}
export interface SalaryRecord {
  'id' : string,
  'memberId' : string,
  'month' : bigint,
  'year' : bigint,
  'distributedAt' : Time,
  'memberName' : string,
  'memberRole' : Role,
  'notes' : [] | [string],
  'amount' : bigint,
}
export type Time = bigint;
export interface UpdateMemberInput {
  'id' : string,
  'name' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'address' : [] | [string],
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMember' : ActorMethod<[Member], string>,
  'distributeSalaries' : ActorMethod<[SalaryDistributionInput], Array<string>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllSalaryRecords' : ActorMethod<[], Array<SalaryRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChildren' : ActorMethod<[string], Array<Member>>,
  'getFullHierarchy' : ActorMethod<[], Array<Member>>,
  'getInquiriesByStatus' : ActorMethod<[InquiryStatus], Array<Inquiry>>,
  'getMember' : ActorMethod<[string], Member>,
  'getSalaryByMonthYear' : ActorMethod<[bigint, bigint], Array<SalaryRecord>>,
  'getSalaryRecords' : ActorMethod<[string], Array<SalaryRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSalary' : ActorMethod<[SalaryInput], string>,
  'submitInquiry' : ActorMethod<[Inquiry], string>,
  'updateInquiryStatus' : ActorMethod<[string, InquiryStatus], undefined>,
  'updateMember' : ActorMethod<[UpdateMemberInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];