/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Property = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'propertyType' : IDL.Text,
  'bedrooms' : IDL.Opt(IDL.Nat),
  'area' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'managingDirector' : IDL.Null,
  'director' : IDL.Null,
  'teamLeader' : IDL.Null,
  'marketingManager' : IDL.Null,
  'bizDev' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'role' : Role,
  'joiningDate' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Text),
});
export const SalaryDistributionInput = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'entries' : IDL.Vec(
    IDL.Record({
      'memberId' : IDL.Text,
      'notes' : IDL.Opt(IDL.Text),
      'amount' : IDL.Nat,
    })
  ),
});
export const InquiryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'contacted' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const InquiryType = IDL.Variant({
  'investment' : IDL.Null,
  'loanApplication' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : InquiryStatus,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Opt(IDL.Nat),
});
export const SalaryRecord = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Text,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'distributedAt' : Time,
  'memberName' : IDL.Text,
  'memberRole' : Role,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CompanyInfo = IDL.Record({
  'about' : IDL.Text,
  'mission' : IDL.Text,
  'tagline' : IDL.Text,
  'established' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'vision' : IDL.Text,
  'phone1' : IDL.Text,
  'phone2' : IDL.Text,
});
export const SalaryInput = IDL.Record({
  'memberId' : IDL.Text,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UpdateMemberInput = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Opt(IDL.Text),
  'joiningDate' : IDL.Opt(IDL.Text),
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addProperty' : IDL.Func([IDL.Text, IDL.Text, Property], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createMember' : IDL.Func([IDL.Text, IDL.Text, Member], [IDL.Text], []),
  'deleteProperty' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'distributeSalaries' : IDL.Func(
      [IDL.Text, IDL.Text, SalaryDistributionInput],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChildren' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
  'getCompanyInfo' : IDL.Func([], [IDL.Opt(CompanyInfo)], ['query']),
  'getFullHierarchy' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getInquiriesByStatus' : IDL.Func(
      [InquiryStatus],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getSalaryByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getSalaryRecords' : IDL.Func([IDL.Text], [IDL.Vec(SalaryRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'removeAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSalary' : IDL.Func([IDL.Text, IDL.Text, SalaryInput], [IDL.Text], []),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
  'updateCompanyInfo' : IDL.Func([IDL.Text, IDL.Text, CompanyInfo], [], []),
  'updateInquiryStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, InquiryStatus],
      [],
      [],
    ),
  'updateMember' : IDL.Func([IDL.Text, IDL.Text, UpdateMemberInput], [], []),
  'updateProperty' : IDL.Func([IDL.Text, IDL.Text, Property], [], []),
  'updateServices' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Service)], [], []),
  'verifyAdminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Property = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'propertyType' : IDL.Text,
    'bedrooms' : IDL.Opt(IDL.Nat),
    'area' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'managingDirector' : IDL.Null,
    'director' : IDL.Null,
    'teamLeader' : IDL.Null,
    'marketingManager' : IDL.Null,
    'bizDev' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'role' : Role,
    'joiningDate' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const SalaryDistributionInput = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'entries' : IDL.Vec(
      IDL.Record({
        'memberId' : IDL.Text,
        'notes' : IDL.Opt(IDL.Text),
        'amount' : IDL.Nat,
      })
    ),
  });
  const InquiryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'contacted' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const InquiryType = IDL.Variant({
    'investment' : IDL.Null,
    'loanApplication' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : InquiryStatus,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Opt(IDL.Nat),
  });
  const SalaryRecord = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Text,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'distributedAt' : Time,
    'memberName' : IDL.Text,
    'memberRole' : Role,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CompanyInfo = IDL.Record({
    'about' : IDL.Text,
    'mission' : IDL.Text,
    'tagline' : IDL.Text,
    'established' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'vision' : IDL.Text,
    'phone1' : IDL.Text,
    'phone2' : IDL.Text,
  });
  const SalaryInput = IDL.Record({
    'memberId' : IDL.Text,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UpdateMemberInput = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Opt(IDL.Text),
    'joiningDate' : IDL.Opt(IDL.Text),
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addProperty' : IDL.Func([IDL.Text, IDL.Text, Property], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createMember' : IDL.Func([IDL.Text, IDL.Text, Member], [IDL.Text], []),
    'deleteProperty' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'distributeSalaries' : IDL.Func(
        [IDL.Text, IDL.Text, SalaryDistributionInput],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChildren' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
    'getCompanyInfo' : IDL.Func([], [IDL.Opt(CompanyInfo)], ['query']),
    'getFullHierarchy' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getInquiriesByStatus' : IDL.Func(
        [InquiryStatus],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getSalaryByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getSalaryRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'removeAdmin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSalary' : IDL.Func([IDL.Text, IDL.Text, SalaryInput], [IDL.Text], []),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
    'updateCompanyInfo' : IDL.Func([IDL.Text, IDL.Text, CompanyInfo], [], []),
    'updateInquiryStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, InquiryStatus],
        [],
        [],
      ),
    'updateMember' : IDL.Func([IDL.Text, IDL.Text, UpdateMemberInput], [], []),
    'updateProperty' : IDL.Func([IDL.Text, IDL.Text, Property], [], []),
    'updateServices' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Service)], [], []),
    'verifyAdminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };