/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Role = IDL.Variant({
  'managingDirector' : IDL.Null,
  'director' : IDL.Null,
  'teamLeader' : IDL.Null,
  'marketingManager' : IDL.Null,
  'bizDev' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : Role,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'parentId' : IDL.Opt(IDL.Text),
});
export const SalaryDistributionInput = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'entries' : IDL.Vec(
    IDL.Record({
      'memberId' : IDL.Text,
      'notes' : IDL.Opt(IDL.Text),
      'amount' : IDL.Nat,
    })
  ),
});
export const InquiryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'contacted' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const InquiryType = IDL.Variant({
  'investment' : IDL.Null,
  'loanApplication' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'status' : InquiryStatus,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'amount' : IDL.Opt(IDL.Nat),
});
export const SalaryRecord = IDL.Record({
  'id' : IDL.Text,
  'memberId' : IDL.Text,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'distributedAt' : Time,
  'memberName' : IDL.Text,
  'memberRole' : Role,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const SalaryInput = IDL.Record({
  'memberId' : IDL.Text,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const UpdateMemberInput = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMember' : IDL.Func([Member], [IDL.Text], []),
  'distributeSalaries' : IDL.Func(
      [SalaryDistributionInput],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChildren' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
  'getFullHierarchy' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getInquiriesByStatus' : IDL.Func(
      [InquiryStatus],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getMember' : IDL.Func([IDL.Text], [Member], ['query']),
  'getSalaryByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(SalaryRecord)],
      ['query'],
    ),
  'getSalaryRecords' : IDL.Func([IDL.Text], [IDL.Vec(SalaryRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSalary' : IDL.Func([SalaryInput], [IDL.Text], []),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
  'updateInquiryStatus' : IDL.Func([IDL.Text, InquiryStatus], [], []),
  'updateMember' : IDL.Func([UpdateMemberInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Role = IDL.Variant({
    'managingDirector' : IDL.Null,
    'director' : IDL.Null,
    'teamLeader' : IDL.Null,
    'marketingManager' : IDL.Null,
    'bizDev' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : Role,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'parentId' : IDL.Opt(IDL.Text),
  });
  const SalaryDistributionInput = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'entries' : IDL.Vec(
      IDL.Record({
        'memberId' : IDL.Text,
        'notes' : IDL.Opt(IDL.Text),
        'amount' : IDL.Nat,
      })
    ),
  });
  const InquiryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'contacted' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const InquiryType = IDL.Variant({
    'investment' : IDL.Null,
    'loanApplication' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'status' : InquiryStatus,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'amount' : IDL.Opt(IDL.Nat),
  });
  const SalaryRecord = IDL.Record({
    'id' : IDL.Text,
    'memberId' : IDL.Text,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'distributedAt' : Time,
    'memberName' : IDL.Text,
    'memberRole' : Role,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SalaryInput = IDL.Record({
    'memberId' : IDL.Text,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const UpdateMemberInput = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMember' : IDL.Func([Member], [IDL.Text], []),
    'distributeSalaries' : IDL.Func(
        [SalaryDistributionInput],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllSalaryRecords' : IDL.Func([], [IDL.Vec(SalaryRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChildren' : IDL.Func([IDL.Text], [IDL.Vec(Member)], ['query']),
    'getFullHierarchy' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getInquiriesByStatus' : IDL.Func(
        [InquiryStatus],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getMember' : IDL.Func([IDL.Text], [Member], ['query']),
    'getSalaryByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getSalaryRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSalary' : IDL.Func([SalaryInput], [IDL.Text], []),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
    'updateInquiryStatus' : IDL.Func([IDL.Text, InquiryStatus], [], []),
    'updateMember' : IDL.Func([UpdateMemberInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };