/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SalaryRecord {
    id: string;
    memberId: string;
    month: bigint;
    year: bigint;
    distributedAt: Time;
    memberName: string;
    memberRole: Role;
    notes?: string;
    amount: bigint;
}
export interface UpdateMemberInput {
    id: string;
    name: string;
    photoUrl?: string;
    email: string;
    address?: string;
    phone: string;
}
export type Time = bigint;
export interface SalaryDistributionInput {
    month: bigint;
    year: bigint;
    entries: Array<{
        memberId: string;
        notes?: string;
        amount: bigint;
    }>;
}
export interface Member {
    id: string;
    name: string;
    createdAt: Time;
    role: Role;
    photoUrl?: string;
    email: string;
    address?: string;
    phone: string;
    parentId?: string;
}
export interface Inquiry {
    id: string;
    status: InquiryStatus;
    inquiryType: InquiryType;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
    amount?: bigint;
}
export interface SalaryInput {
    memberId: string;
    month: bigint;
    year: bigint;
    notes?: string;
    amount: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum InquiryStatus {
    pending = "pending",
    contacted = "contacted",
    reviewed = "reviewed"
}
export enum InquiryType {
    investment = "investment",
    loanApplication = "loanApplication"
}
export enum Role {
    managingDirector = "managingDirector",
    director = "director",
    teamLeader = "teamLeader",
    marketingManager = "marketingManager",
    bizDev = "bizDev"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMember(member: Member): Promise<string>;
    distributeSalaries(input: SalaryDistributionInput): Promise<Array<string>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllSalaryRecords(): Promise<Array<SalaryRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChildren(parentId: string): Promise<Array<Member>>;
    getFullHierarchy(): Promise<Array<Member>>;
    getInquiriesByStatus(status: InquiryStatus): Promise<Array<Inquiry>>;
    getMember(id: string): Promise<Member>;
    getSalaryByMonthYear(month: bigint, year: bigint): Promise<Array<SalaryRecord>>;
    getSalaryRecords(memberId: string): Promise<Array<SalaryRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setSalary(input: SalaryInput): Promise<string>;
    submitInquiry(inquiry: Inquiry): Promise<string>;
    updateInquiryStatus(id: string, status: InquiryStatus): Promise<void>;
    updateMember(input: UpdateMemberInput): Promise<void>;
}
import type { Inquiry as _Inquiry, InquiryStatus as _InquiryStatus, InquiryType as _InquiryType, Member as _Member, Role as _Role, SalaryDistributionInput as _SalaryDistributionInput, SalaryInput as _SalaryInput, SalaryRecord as _SalaryRecord, Time as _Time, UpdateMemberInput as _UpdateMemberInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMember(arg0: Member): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMember(to_candid_Member_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMember(to_candid_Member_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async distributeSalaries(arg0: SalaryDistributionInput): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.distributeSalaries(to_candid_SalaryDistributionInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.distributeSalaries(to_candid_SalaryDistributionInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalaryRecords(): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalaryRecords();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalaryRecords();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildren(arg0: string): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildren(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildren(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFullHierarchy(): Promise<Array<Member>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFullHierarchy();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFullHierarchy();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInquiriesByStatus(arg0: InquiryStatus): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInquiriesByStatus(to_candid_InquiryStatus_n31(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInquiriesByStatus(to_candid_InquiryStatus_n31(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMember(arg0: string): Promise<Member> {
        if (this.processError) {
            try {
                const result = await this.actor.getMember(arg0);
                return from_candid_Member_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMember(arg0);
            return from_candid_Member_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalaryByMonthYear(arg0: bigint, arg1: bigint): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaryByMonthYear(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaryByMonthYear(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalaryRecords(arg0: string): Promise<Array<SalaryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalaryRecords(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalaryRecords(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setSalary(arg0: SalaryInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.setSalary(to_candid_SalaryInput_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSalary(to_candid_SalaryInput_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitInquiry(arg0: Inquiry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(to_candid_Inquiry_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(to_candid_Inquiry_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInquiryStatus(arg0: string, arg1: InquiryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_InquiryStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMember(arg0: UpdateMemberInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMember(to_candid_UpdateMemberInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMember(to_candid_UpdateMemberInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_InquiryStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryStatus): InquiryStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Member_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Member): Member {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SalaryRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalaryRecord): SalaryRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _InquiryStatus;
    inquiryType: _InquiryType;
    name: string;
    createdAt: _Time;
    email: string;
    message: string;
    phone: string;
    amount: [] | [bigint];
}): {
    id: string;
    status: InquiryStatus;
    inquiryType: InquiryType;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
    amount?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InquiryStatus_n14(_uploadFile, _downloadFile, value.status),
        inquiryType: from_candid_InquiryType_n16(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        message: value.message,
        phone: value.phone,
        amount: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    memberId: string;
    month: bigint;
    year: bigint;
    distributedAt: _Time;
    memberName: string;
    memberRole: _Role;
    notes: [] | [string];
    amount: bigint;
}): {
    id: string;
    memberId: string;
    month: bigint;
    year: bigint;
    distributedAt: Time;
    memberName: string;
    memberRole: Role;
    notes?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        memberId: value.memberId,
        month: value.month,
        year: value.year,
        distributedAt: value.distributedAt,
        memberName: value.memberName,
        memberRole: from_candid_Role_n22(_uploadFile, _downloadFile, value.memberRole),
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: _Time;
    role: _Role;
    photoUrl: [] | [string];
    email: string;
    address: [] | [string];
    phone: string;
    parentId: [] | [string];
}): {
    id: string;
    name: string;
    createdAt: Time;
    role: Role;
    photoUrl?: string;
    email: string;
    address?: string;
    phone: string;
    parentId?: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n22(_uploadFile, _downloadFile, value.role),
        photoUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.photoUrl)),
        email: value.email,
        address: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.address)),
        phone: value.phone,
        parentId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    contacted: null;
} | {
    reviewed: null;
}): InquiryStatus {
    return "pending" in value ? InquiryStatus.pending : "contacted" in value ? InquiryStatus.contacted : "reviewed" in value ? InquiryStatus.reviewed : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    investment: null;
} | {
    loanApplication: null;
}): InquiryType {
    return "investment" in value ? InquiryType.investment : "loanApplication" in value ? InquiryType.loanApplication : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    managingDirector: null;
} | {
    director: null;
} | {
    teamLeader: null;
} | {
    marketingManager: null;
} | {
    bizDev: null;
}): Role {
    return "managingDirector" in value ? Role.managingDirector : "director" in value ? Role.director : "teamLeader" in value ? Role.teamLeader : "marketingManager" in value ? Role.marketingManager : "bizDev" in value ? Role.bizDev : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalaryRecord>): Array<SalaryRecord> {
    return value.map((x)=>from_candid_SalaryRecord_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Member>): Array<Member> {
    return value.map((x)=>from_candid_Member_n29(_uploadFile, _downloadFile, x));
}
function to_candid_InquiryStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): _InquiryStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Inquiry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Inquiry): _Inquiry {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Member_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Member): _Member {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SalaryDistributionInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalaryDistributionInput): _SalaryDistributionInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SalaryInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalaryInput): _SalaryInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMemberInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMemberInput): _UpdateMemberInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: string;
    notes?: string;
    amount: bigint;
}): {
    memberId: string;
    notes: [] | [string];
    amount: bigint;
} {
    return {
        memberId: value.memberId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: string;
    month: bigint;
    year: bigint;
    notes?: string;
    amount: bigint;
}): {
    memberId: string;
    month: bigint;
    year: bigint;
    notes: [] | [string];
    amount: bigint;
} {
    return {
        memberId: value.memberId,
        month: value.month,
        year: value.year,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: InquiryStatus;
    inquiryType: InquiryType;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
    amount?: bigint;
}): {
    id: string;
    status: _InquiryStatus;
    inquiryType: _InquiryType;
    name: string;
    createdAt: _Time;
    email: string;
    message: string;
    phone: string;
    amount: [] | [bigint];
} {
    return {
        id: value.id,
        status: to_candid_InquiryStatus_n31(_uploadFile, _downloadFile, value.status),
        inquiryType: to_candid_InquiryType_n37(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        message: value.message,
        phone: value.phone,
        amount: value.amount ? candid_some(value.amount) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: Time;
    role: Role;
    photoUrl?: string;
    email: string;
    address?: string;
    phone: string;
    parentId?: string;
}): {
    id: string;
    name: string;
    createdAt: _Time;
    role: _Role;
    photoUrl: [] | [string];
    email: string;
    address: [] | [string];
    phone: string;
    parentId: [] | [string];
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_Role_n5(_uploadFile, _downloadFile, value.role),
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        email: value.email,
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    photoUrl?: string;
    email: string;
    address?: string;
    phone: string;
}): {
    id: string;
    name: string;
    photoUrl: [] | [string];
    email: string;
    address: [] | [string];
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        email: value.email,
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    month: bigint;
    year: bigint;
    entries: Array<{
        memberId: string;
        notes?: string;
        amount: bigint;
    }>;
}): {
    month: bigint;
    year: bigint;
    entries: Array<{
        memberId: string;
        notes: [] | [string];
        amount: bigint;
    }>;
} {
    return {
        month: value.month,
        year: value.year,
        entries: to_candid_vec_n9(_uploadFile, _downloadFile, value.entries)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryStatus): {
    pending: null;
} | {
    contacted: null;
} | {
    reviewed: null;
} {
    return value == InquiryStatus.pending ? {
        pending: null
    } : value == InquiryStatus.contacted ? {
        contacted: null
    } : value == InquiryStatus.reviewed ? {
        reviewed: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    investment: null;
} | {
    loanApplication: null;
} {
    return value == InquiryType.investment ? {
        investment: null
    } : value == InquiryType.loanApplication ? {
        loanApplication: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    managingDirector: null;
} | {
    director: null;
} | {
    teamLeader: null;
} | {
    marketingManager: null;
} | {
    bizDev: null;
} {
    return value == Role.managingDirector ? {
        managingDirector: null
    } : value == Role.director ? {
        director: null
    } : value == Role.teamLeader ? {
        teamLeader: null
    } : value == Role.marketingManager ? {
        marketingManager: null
    } : value == Role.bizDev ? {
        bizDev: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    memberId: string;
    notes?: string;
    amount: bigint;
}>): Array<{
    memberId: string;
    notes: [] | [string];
    amount: bigint;
}> {
    return value.map((x)=>to_candid_record_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
